name: Working with environment variables

on:
  push:
    branches:
      - develop

env:
  GLOBAL_VARIABLE: Global Variable

jobs:
  env-var1:
    env:
      JOB_LEVEL_VARIABLE: Job Level Variable
    name: Env Variables1
    runs-on: ubuntu-latest
    steps:
      - name: All Env Variables
        env:
          STEP_LEVEL_VARIABLE: Step Level Variable
        run: |
          echo "Global Env Variable: ${GLOBAL_VARIABLE}"
          echo "Job Level Env Variable: ${JOB_LEVEL_VARIABLE}"
          echo "Step Level Env Variable: ${STEP_LEVEL_VARIABLE}"
      - name: Failes at Step Level Environment Variable
        run: |
          echo "Global Env Variable: ${GLOBAL_VARIABLE}"
          echo "Job Level Env Variable: ${JOB_LEVEL_VARIABLE}"
          echo "Step Level Env Variable: ${STEP_LEVEL_VARIABLE}"
  env-var2:
    name: Env Variables2
    runs-on: ubuntu-latest
    steps:
      - name: Failes at Job and Step Level Environment Variable
        run: |
          echo "Global Env Variable: ${GLOBAL_VARIABLE}"
          echo "Job Level Env Variable: ${JOB_LEVEL_VARIABLE}"
          echo "Step Level Env Variable: ${STEP_LEVEL_VARIABLE}"
  env-var3:
    name: Global Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Printing Global Environment Variables
        run: |
          echo ${CI}
          echo ${HOME}
          echo ${GITHUB_WORKFLOW}
          echo ${GITHUB_RUN_ID}
          echo ${GITHUB_RUN_NUMBER}
          echo ${GITHUB_ACTION}
          echo ${GITHUB_ACTIONS}
          echo ${GITHUB_ACTOR}
          echo ${GITHUB_REPOSITORY}
          echo ${GITHUB_EVENT_NAME}
          echo ${GITHUB_EVENT_PATH}
          echo ${GITHUB_WORKSPACE}
          echo ${GITHUB_SHA}
          echo ${GITHUB_REF}
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_BASE_REF}
