name: Hello World Javascript Action

on: push

jobs:
  hello-js-action:
    runs-on: ubuntu-latest
    steps:
      - name: Hello JS Action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: "Khaja"
      - name: Run JS Action
        run: echo "${{ steps.hello.outputs.time }}"
