name: Hello World Example

on: push

jobs:
  hello-world:
    name: Hello World
    runs-on: ubuntu-latest
    env:
      VALUE: Hello World2
    steps:
      - name: Echo Hello World Static
        run: echo "Hello World1"
