name: Hello World Github Actions Demo

on: push

jobs:
  hello-world:
    name: Hello world job
    runs-on: ubuntu-latest
    steps:
      - name: Hello World Step
        run: |
          echo "Hello World"
