name: Events Demo

on:
  # push:
  #   branches: [master, develop]
  pull_request:
    branches: [develop, pull_request]
    types: ["opened", "edited", "closed"]

jobs:
  events-demo:
    runs-on: ubuntu-latest
    name: Various Events Demo
    steps:
      - name: Opened Event
        run: |
          echo "Opened Event"
