name: Events Demo

on:
  # schedule:
  #   - 5 * * * *
  # push:
  #   branches:
  #     - master
  #     - "!develop"
  #   paths:
  #     - "**.js"
  #     - "**.css"
  #     - "!**.md"
  #   tags:
  #     - "v2.0"
  #     - "!v1.*"
  pull_request:
    branches: [develop, master]
    types: ["opened", "edited", "closed"]

jobs:
  events-demo:
    runs-on: ubuntu-latest
    name: Various Events Demo
    steps:
      - name: Opened Event
        run: |
          echo "Opened Event"
