name: Shell Commands

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    env:
      name: hello
    steps:
      - name: Echo a string
        run: |
          echo "Hello World"
          echo ${{ GITHUB_REPOSITORY }}
          echo ${{ run-shell-command.name }}

      - name: Multiline Script
        run: |
          node -v
          npm -v
      - name: Python Command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: Powershell Directory
        run: Get-Location
      - name: Bash Directory
        run: pwd
        shell: bash
